# Generated by Django 4.2.13 on 2024-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
