# Generated by Django 4.2.13 on 2024-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_remove_userprofile_email_userprofile_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
