# Generated by Django 4.2.13 on 2024-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_alter_userprofile_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mail',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
