# Generated by Django 4.2.13 on 2024-06-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0008_userprofile_image_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
