# Generated by Django 4.2.13 on 2024-06-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0011_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review_text',
        ),
    ]
