# Generated by Django 4.2.13 on 2024-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0013_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
